framework:
  rate_limiter:
    contact_form:
      policy: 'sliding_window'
      limit: 5
      interval: '10 minutes'

    newsletter_subscribe:
        policy: sliding_window
        limit: 3
        interval: '10 minutes'

    newsletter_sending:
        policy: fixed_window
        limit: 20
        interval: '1 minute'