services:
  Redis:
    class: Redis
    calls:
      - connect:
          - redis
          - 6379

  Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
    arguments:
      - '@Redis'